# Question 1 problem #1

In [17]:
def function_1(L): 
    '''Function for finding mean,max and min of list L'''
    minimum = min(L)
    maximum = max(L)
    mean =sum(L)/len(L)
    print("min =", min(L),"max = ", max(L),"average =", (sum(L)/len(L)))
 #yes we can use the function we just defined, in one line
function_1 ([10,14,50])

min = 10 max =  50 average = 24.666666666666668


# Question 1 problem #2


In [18]:
#test for immutability of integers
a = 10
b = a
b = 3
a == b
#integers are immutable

False

In [19]:
print(a,b)

10 3


In [20]:
#test for immutability of list
m=["mahyar", 10, 23,64]
f = m
m[3]=130000
f[0]= list([1, 2])
m == f

True

In [21]:
print(m)# lists are mutable 

[[1, 2], 10, 23, 130000]


In [22]:
#test for immutability of list
c = 'Work Hard Be Nice!'
d = c
d = 12345
c == d

False

In [23]:
print(c,d)# strings are immutable

Work Hard Be Nice! 12345


In [24]:
#test for immutability of tuples
g = ("Happy", 10, 5, 4) #tuples are immutable 
h = g
h += ('5',)
h == g

False

In [25]:
print(g,h)#tuples are immutable 

('Happy', 10, 5, 4) ('Happy', 10, 5, 4, '5')


In [26]:
#test for immutability of tuples
myset = {"Happy", 4, 10}
set_2 = myset
set_2 -= {1}
myset == set_2
#or
set1={"red","blue","green","red"}
set1.add("yellow")
set1.update([1,2,3,4])

In [27]:
print(set_1,set_2,set1,",repeated item   eliminated automatically")#sets are mutable

NameError: name 'set_1' is not defined

# Question 1 problem 3

In [28]:
import calculator as cal
def fhypotenuse(m, n):
    alpha = cal.fmultp(m, m)
    beta = cal.fmultp(n, n)
    print(cal.sqrt(cal.fsums(alpha, beta)))
fhypotenuse(3,4)

5.0


# Question 2 problem 1

In [29]:
#By using np.dot
import numpy as np
def MMULT(A, B):
    return np.dot(np.array(A), np.array(B))
A = [[3, -1, 4], [1, 5, -9]]
B = [[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]]
MMULT(A, B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [30]:
#BY USING np.mat(A,B)
import numpy as np
def Matway(M,N):
    return np.array(np.mat(M)*np.mat(N),subok=True)
M,N ='3 -1 4; 1 5 -9','2 6 -5 3; 5 -8 9 7; 9 -3 -2 -3'
Matway(M,N)

matrix([[ 37,  14, -32, -10],
        [-54,  -7,  58,  65]])

# Question 2 problem 2


In [31]:
import numpy as np
def g(A):
    A = np.array(A)
    R = (-A * A * A) + (9 * A * A) - (15 * A)
    return R
A = [[3, 1, 4], [1, 5, 9], [-5, 3, 1]]
g(A)

array([[   9,   -7,   20],
       [  -7,   25, -135],
       [ 425,    9,   -7]])

#  Question 2 problem 5

In [32]:
import numpy as np
def blockmatrix(A, B, C):
    A = np.array(A)
    B = np.array(B)
    C = np.array(C)
    row1 = np.column_stack((np.zeros((3,3)), A.T, np.eye((3))))
    row2 = np.column_stack((A, np.zeros((2, 2)), np.zeros((2, 3))))
    row3 = np.column_stack((B, np.zeros((3,2)), C))
    print(np.vstack((row1, row2, row3)))

In [33]:
A = [[0, 2, 4], [1, 3, 5]]
B = [[3, 0, 0], [3, 3, 0], [3, 3, 3]]
C = [[-2, 0, 0], [0, -2, 0], [0, 0, -2]]
blockmatrix(A, B, C)

[[ 0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0. -2.  0.  0.]
 [ 3.  3.  0.  0.  0.  0. -2.  0.]
 [ 3.  3.  3.  0.  0.  0.  0. -2.]]


In [37]:
# or #I think matrices' dimensions are correct but I don't know why I got 
#'invalid syntax error'
import numpy as np
def blockmax(M,N,G):
    M = np.array(M)
    N = np.array(N)
    G = np.array(G)
    column_one = np.vstack(((np.zeros((3,3)),M,N))
    column_two = np.vstack((M.T,np.zeros((2,2)),np.zeros((3,2))))
    column_three = np.vstack((np.eye((3)),np.zeros((2, 3)),G)))
    print(np.hstack((column_one,column_two,column_three)))

SyntaxError: invalid syntax (<ipython-input-37-4fb7fa2e6e90>, line 9)

In [34]:
M = [[0, 2, 4], [1, 3, 5]]
N = [[3, 0, 0], [3, 3, 0], [3, 3, 3]]
G = [[-2, 0, 0], [0, -2, 0], [0, 0, -2]]        
blockmax(A, B, C) 

NameError: name 'blockmax' is not defined

# Question 3 problem 1


In [45]:
class Backpack(object):    #Part 1
    def __init__(self, name, color, max_size = 5):
        '''
        (part 4) object class. including a name, a color, 
        and maximum size for contents and a content list.

        Attributes:
             name (string) : name of the backpack's owner.
             color (string) : color of the backpack.
             max_size (integer) : the maximum size of the backpack.
             contents (list) : contents of the backpack.
        '''
        self.name = name
        self.contents = []
        self.color = color
        self.max_size = max_size

    def put(self, item):    #part 2
        if len(self.contents) >= self.max_size:
            print("No Room!")
        else:
            self.contents.append(item)

    def dump(self):    #part 3
        self.contents = []

#-----------------------------------------------------------------
#-----------------------------------------------------------------
testpack = Backpack("Mahyar", "Blue")
for item in ["pen", "pencil", "notebook", "laptop", "mouse", "umbrella"]:
    testpack.put(item)
print("contents: ", testpack.contents)
# no room for "umbrella"!

No Room!
contents:  ['pen', 'pencil', 'notebook', 'laptop', 'mouse']


In [39]:
testpack.dump()
print("contents: ", testpack.contents)

contents:  []


# Question 3 problem 2

In [40]:
# Backpack object class, attributes and details are explained and constructed in previous lines in problem 1.
# First run Problem 1, Backpack class. 

########################################################################
########################################################################

class Jetpack(Backpack):
    """
    A Jetpack object class. Inherited from Backpack class.
    A Jetpack is smaller than a Backpackself.

    Attributes:
        name (str): the name of the Jetpack's owner.
        color (str): color of Jetpack
        max_size (int): maximum number of items that can be fit inside the Jetpack
        fuel (int):
        contents (list): the contents of the Jetpack
    """
    def __init__(self, name, color, max_size = 2, fuel =10):
        Backpack.__init__(self, name, color, max_size)
        self.fuel = fuel

    def fly(self, burned_fuel):
        self.burned_fuel = burned_fuel
        if self.burned_fuel <= self.fuel:
            self.fuel = self.fuel - self.burned_fuel
        if self.burned_fuel > self.fuel:
            self.fuel = self.fuel
            print("Not Enough Fuel!")
    def dump(self):
        Backpack.dump(self)
        self.fuel = 0

In [41]:
test = Jetpack("Mahyar", "White")
test.put("calculator")
print(test.contents, test.fuel)

['calculator'] 10


In [42]:
test.dump()
print(test.contents, test.fuel)

[] 0


In [43]:
for item in ["pen", "pencil", "notebook"]:
    test.put(item)
print(test.contents, test.fuel)

No Room!
['pen', 'pencil'] 0


In [44]:
test.fly(1)
print(test.contents, test.fuel)

Not Enough Fuel!
['pen', 'pencil'] 0
